spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE-BOOT
          predicates:
            - Path=/v1/user-service/**
          filters:
            - RewritePath=/v1/user-service/(?<remains>.*), /$\{remains}
            - name: Hystrix
              args:
                name: hystrix
                fallbackUri: forward:/fallback/users
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: hystrixAuth
                fallbackUri: forward:/fallback/auth
  application:
    name: cloud-api-gateway
hystrix.command.hystrix.execution.isolation.thread.timeoutInMilliseconds: 5000
server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'