spring:
  application:
    name: customer-service
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 100

server:
  port: 8088

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


