eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: user-service-boot
hystrix:
  metrics:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
#      base-path: /
server:
  port: 8090
